#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=9

# Values live in the repo's .env (already gitignored), not the cwd's.
REPO_ROOT=$(git -C "$(dirname "${BASH_SOURCE[0]}")" rev-parse --show-toplevel 2>/dev/null || pwd)
ENV_FILE="$REPO_ROOT/.env"
CF_DIR="$HOME/.cloudflared"

banner "Perfect Tuition — Cloudflare Tunnel setup"

# ── Stage 1 ───────────────────────────────────────────────────────────────
stage "Confirm the targets"
say "Nothing is changed in this stage — we just settle the names everything else uses."
note "Values are saved to $ENV_FILE, which .gitignore already covers."
ask TUNNEL_DOMAIN   "Domain (Enter for perfect-tuition.co.in):"
[[ -z "$TUNNEL_DOMAIN" ]] && TUNNEL_DOMAIN="perfect-tuition.co.in"
ask API_PORT        "Local port the Hono API will listen on (Enter for 3000):"
[[ -z "$API_PORT" ]] && API_PORT="3000"
ask TUNNEL_NAME     "Tunnel name (Enter for perfect-tuition-api):"
[[ -z "$TUNNEL_NAME" ]] && TUNNEL_NAME="perfect-tuition-api"
TUNNEL_HOSTNAME="api.${TUNNEL_DOMAIN}"
write_env TUNNEL_DOMAIN   "$TUNNEL_DOMAIN"
write_env TUNNEL_HOSTNAME "$TUNNEL_HOSTNAME"
write_env API_PORT        "$API_PORT"
write_env TUNNEL_NAME     "$TUNNEL_NAME"
say ""
say "Will route  https://${TUNNEL_HOSTNAME}  →  http://localhost:${API_PORT}"
pause "Looks right?"

# ── Stage 2 ───────────────────────────────────────────────────────────────
stage "Install cloudflared"
if command -v cloudflared >/dev/null 2>&1; then
  say "Already installed: $(cloudflared --version 2>&1 | head -1)"
else
  say "Installing from Cloudflare's apt repository. This needs sudo."
  note "Using the 'any' distribution — this machine's codename ($(. /etc/os-release && echo "$VERSION_CODENAME")) has no per-codename repo."
  if confirm "Install cloudflared now?"; then
    sudo mkdir -p --mode=0755 /usr/share/keyrings
    curl -fsSL https://pkg.cloudflare.com/cloudflare-main.gpg \
      | sudo tee /usr/share/keyrings/cloudflare-main.gpg >/dev/null
    echo 'deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared any main' \
      | sudo tee /etc/apt/sources.list.d/cloudflared.list >/dev/null
    if ! (sudo apt-get update -qq && sudo apt-get install -y cloudflared); then
      warn "apt install failed — falling back to the .deb release."
      tmpdeb=$(mktemp --suffix=.deb)
      curl -fsSL -o "$tmpdeb" https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
      sudo dpkg -i "$tmpdeb"
      rm -f "$tmpdeb"
    fi
  else
    SKIPPED+=("install cloudflared"); warn "skipped — later stages will fail without it."
  fi
fi
command -v cloudflared >/dev/null 2>&1 && say "✓ $(cloudflared --version 2>&1 | head -1)"
pause

# ── Stage 3 ───────────────────────────────────────────────────────────────
stage "Authenticate with Cloudflare"
if [[ -f "$CF_DIR/cert.pem" ]]; then
  say "Already authenticated — $CF_DIR/cert.pem exists."
else
  say "A browser window will open. Log in, then pick the zone for ${TUNNEL_DOMAIN}."
  warn "Pick the DOMAIN itself, not 'All zones' — the cert is scoped to what you select."
  pause "Press Enter to start the login flow"
  cloudflared tunnel login || warn "login command returned non-zero — check the output above."
fi
if [[ -f "$CF_DIR/cert.pem" ]]; then
  say "✓ certificate at $CF_DIR/cert.pem"
else
  warn "No cert.pem found. The next stages cannot succeed until login completes."
  SKIPPED+=("cloudflared tunnel login")
fi
pause

# ── Stage 4 ───────────────────────────────────────────────────────────────
stage "Create the tunnel"
existing_id=$(cloudflared tunnel list 2>/dev/null | awk -v n="$TUNNEL_NAME" '$2==n {print $1; exit}' || true)
if [[ -n "$existing_id" ]]; then
  say "Tunnel '$TUNNEL_NAME' already exists — reusing it."
  TUNNEL_ID="$existing_id"
else
  cloudflared tunnel create "$TUNNEL_NAME" || warn "create failed — see output above."
  TUNNEL_ID=$(cloudflared tunnel list 2>/dev/null | awk -v n="$TUNNEL_NAME" '$2==n {print $1; exit}' || true)
fi
if [[ -z "${TUNNEL_ID:-}" ]]; then
  warn "Couldn't read the tunnel ID automatically."
  ask TUNNEL_ID "Paste the tunnel UUID from the output above:"
fi
TUNNEL_CREDENTIALS_FILE="$CF_DIR/${TUNNEL_ID}.json"
write_env TUNNEL_ID "$TUNNEL_ID"
write_env TUNNEL_CREDENTIALS_FILE "$TUNNEL_CREDENTIALS_FILE"
say "✓ tunnel $TUNNEL_NAME → $TUNNEL_ID"
if [[ -f "$TUNNEL_CREDENTIALS_FILE" ]]; then
  say "✓ credentials at $TUNNEL_CREDENTIALS_FILE"
else
  warn "Expected credentials file not found at $TUNNEL_CREDENTIALS_FILE"
fi
warn "That credentials file IS the tunnel's secret. It stays in $CF_DIR — never copy it into the repo."
pause

# ── Stage 5 ───────────────────────────────────────────────────────────────
stage "Write the ingress config"
say "Routing ${TUNNEL_HOSTNAME} to the local API, and refusing everything else."
mkdir -p "$CF_DIR"
if [[ -f "$CF_DIR/config.yml" ]] && ! confirm "config.yml exists — overwrite it?"; then
  say "Keeping the existing config."
else
  cat > "$CF_DIR/config.yml" <<EOF
tunnel: ${TUNNEL_ID}
credentials-file: ${TUNNEL_CREDENTIALS_FILE}

ingress:
  - hostname: ${TUNNEL_HOSTNAME}
    service: http://localhost:${API_PORT}
  - service: http_status:404
EOF
  say "✓ wrote $CF_DIR/config.yml"
fi
note "The catch-all 404 matters: without it any hostname pointed at this tunnel would reach your laptop."
pause

# ── Stage 6 ───────────────────────────────────────────────────────────────
stage "Route ${TUNNEL_HOSTNAME} to the tunnel"
say "This creates a PROXIED (orange cloud) CNAME in Cloudflare. Tunnel requires proxying."
if cloudflared tunnel route dns "$TUNNEL_NAME" "$TUNNEL_HOSTNAME"; then
  say "✓ DNS route created"
else
  note "A failure here usually means the record already exists — that's fine."
fi
pause

# ── Stage 7 ───────────────────────────────────────────────────────────────
stage "Point the apex + www at GitHub Pages"
say "These records are DNS-ONLY (grey cloud) so GitHub can issue its own certificate."
warn "Grey cloud is deliberate. Proxying Pages is what causes the redirect loop at launch."
open_url "https://dash.cloudflare.com/?to=/:account/${TUNNEL_DOMAIN}/dns"
step "Add four A records for '@', each grey-clouded:"
note "    185.199.108.153   185.199.109.153   185.199.110.153   185.199.111.153"
step "Add four AAAA records for '@', each grey-clouded:"
note "    2606:50c0:8000::153   2606:50c0:8001::153"
note "    2606:50c0:8002::153   2606:50c0:8003::153"
ask PAGES_HOST "GitHub Pages host (Enter for subhojit-bhattacharya.github.io):"
[[ -z "$PAGES_HOST" ]] && PAGES_HOST="subhojit-bhattacharya.github.io"
write_env PAGES_HOST "$PAGES_HOST"
step "Add a CNAME: name 'www' → ${PAGES_HOST}, grey-clouded."
step "Finally, in Cloudflare → SSL/TLS → Overview, confirm the mode is 'Full'."
note "GitHub Pages is not enabled on the repo yet, so certificate issuance will only"
note "complete once Pages is turned on and the custom domain is set there."
pause "Done adding records?"

# ── Stage 8 ───────────────────────────────────────────────────────────────
stage "Run the tunnel as a service"
say "Installs a systemd unit so the tunnel reconnects on boot and after sleep."
if confirm "Install the cloudflared systemd service? (needs sudo)"; then
  sudo mkdir -p /etc/cloudflared
  sudo cp "$TUNNEL_CREDENTIALS_FILE" "/etc/cloudflared/${TUNNEL_ID}.json"
  sudo tee /etc/cloudflared/config.yml >/dev/null <<EOF
tunnel: ${TUNNEL_ID}
credentials-file: /etc/cloudflared/${TUNNEL_ID}.json

ingress:
  - hostname: ${TUNNEL_HOSTNAME}
    service: http://localhost:${API_PORT}
  - service: http_status:404
EOF
  sudo chmod 600 "/etc/cloudflared/${TUNNEL_ID}.json"
  sudo cloudflared service install || note "already installed — continuing"
  sudo systemctl enable --now cloudflared || true
  sleep 3
  systemctl --no-pager --lines=5 status cloudflared || true
else
  SKIPPED+=("cloudflared systemd service")
fi
pause

# ── Stage 9 ───────────────────────────────────────────────────────────────
stage "Verify, and record the origin-down status"
say "Ticket #5 needs one specific fact: what Cloudflare returns when the laptop is"
say "unreachable. The frontend's WhatsApp fallback is written against it."
say ""
step "First: origin UP. Starting a throwaway listener on port ${API_PORT}..."
python3 -m http.server "$API_PORT" --bind 127.0.0.1 >/dev/null 2>&1 &
probe_pid=$!
sleep 2
up_status="000"
for _ in 1 2 3 4 5 6; do
  up_status=$(curl -s -o /dev/null -w '%{http_code}' --max-time 10 "https://${TUNNEL_HOSTNAME}/" || echo 000)
  [[ "$up_status" == "200" ]] && break
  note "  got $up_status — waiting for DNS/tunnel to settle..."
  sleep 10
done
say "  origin UP  → HTTP $up_status"
kill "$probe_pid" 2>/dev/null || true
wait "$probe_pid" 2>/dev/null || true
sleep 2
step "Now: origin DOWN. Listener stopped."
ORIGIN_DOWN_STATUS=$(curl -s -o /dev/null -w '%{http_code}' --max-time 20 "https://${TUNNEL_HOSTNAME}/" || echo 000)
say "  origin DOWN → HTTP $ORIGIN_DOWN_STATUS"
write_env ORIGIN_DOWN_STATUS "$ORIGIN_DOWN_STATUS"
say ""
if [[ "$up_status" == "200" ]]; then
  say "✓ Tunnel verified end to end."
else
  warn "Origin-up probe never returned 200 — DNS may still be propagating. Re-run this stage later."
fi
note "Record HTTP $ORIGIN_DOWN_STATUS on issue #5 — issue #6 depends on it."
pause

finish
